fix: Remove appium from dev dependencies (#531)

diff --git a/ci-jobs/templates/android-e2e-template.yml b/ci-jobs/templates/android-e2e-template.yml
--- a/ci-jobs/templates/android-e2e-template.yml
+++ b/ci-jobs/templates/android-e2e-template.yml
@@ -24,7 +24,9 @@ jobs:
     - task: NodeTool@0
       inputs:
         versionSpec: ${{ parameters.NODE_VERSION }}
-    - script: npm install --chromedriver_version="${{ parameters.CHROMEDRIVER_VERSION }}"
+    - script:
+        npm install -g appium@next
+        npm install --chromedriver_version="${{ parameters.CHROMEDRIVER_VERSION }}"
       displayName: Install Node dependencies
     - script: npm install --no-save mjpeg-consumer
       displayName: Install MJPEG Consumer
@@ -39,7 +41,30 @@ jobs:
         ANDROID_ARCH: ${{ parameters.ANDROID_ARCH }}
     - script: sleep ${{ parameters.sleep }}
       displayName: Sleep ${{parameters.sleep}} seconds
-    - script: ${{ parameters.script }}
+    - script: |
+        export APPIUM_TEST_SERVER_PORT=4567
+        export APPIUM_TEST_SERVER_HOST=127.0.0.1
+        export cwd=$(pwd)
+        pushd "$cwd"
+        cd ~
+        appium driver install --source=local "$cwd"
+        appium server \
+          --port=$APPIUM_TEST_SERVER_PORT \
+          --address=$APPIUM_TEST_SERVER_HOST \
+          --relaxed-security \
+          &
+        popd
+        secondsStarted=$(date +%s)
+        while ! nc -z $APPIUM_TEST_SERVER_HOST $APPIUM_TEST_SERVER_PORT; do
+          sleep 0.1
+          secondsElapsed=$(( $(date +%s) - secondsStarted ))
+          if [[ $secondsElapsed -gt 30 ]]; then
+            echo "Appium server was unable to start within 30 seconds timeout"
+            exit 1
+          fi
+        done
+
+        ${{ parameters.script }}
       env:
         JAVA_HOME: $(JAVA_HOME_11_X64)
         PATH: $(JAVA_HOME_11_X64)/bin:$(PATH)
